// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fiftyhertz;

import com.fiftyhertz.Generation;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Generation_Roo_Configurable {
    
    declare @type: Generation: @Configurable;
    
}
